# Configure a base URL for the Ollama Server
quarkus.langchain4j.ollama.base-url=http://localhost:11434

# Define model ID which langchain4j will invoke on Ollama Server
quarkus.langchain4j.ollama.chat-model.model-id=gpt-oss:20b
quarkus.langchain4j.ollama.embedding-model.model-id=nomic-embed-text

# --- PgVector Settings ---
quarkus.langchain4j.pgvector.register-vector-pg-extension=true
quarkus.langchain4j.pgvector.dimension=768
quarkus.langchain4j.pgvector.table=travel_embeddings
quarkus.langchain4j.pgvector.drop-table-first=true

# Define the timeout for the call
# If model takes longer than 60s to respond, the call will fail
quarkus.langchain4j.ollama.timeout=600

# Point to the directory that contains our documents.
# Easy RAG will read all files in this directory on startup.
quarkus.langchain4j.easy-rag.path=src/main/resources/rag

# --- Logging Settings of LangChain4J ---
# Logs full request sent to LLM (including Tools' manifest)
quarkus.langchain4j.log-requests=true

# Logs full response received from LLM (including Tool's call)
quarkus.langchain4j.log-responses=true


# Defines a client called "booking-server"
quarkus.langchain4j.mcp.booking-server.transport-type=http
quarkus.langchain4j.mcp.booking-server.url=http://localhost:8081/mcp/sse/


# Logs to enable visibility of the MCP messages
quarkus.langchain4j.mcp.booking-server.log-requests=true
quarkus.langchain4j.mcp.booking-server.log-responses=true

# Maximum retries for autocorrection before throwing an exception
quarks.langchain4j.guadrails.max-retries=3




